artifacts:
  home: /path/to/keep/ore/downloaded/artifacts
jfrog:
  default:
    url: https://jfrog1.example.com/api/storage
    user: jfroguser1:jfrogpassword1

download:
  default:
    url:
    - name: python-windows
      urls:
        - url: https://www.python.org/ftp/python/3.13.3/python-3.13.3-amd64.exe
        - url: https://www.python.org/ftp/python/3.12.10/python-3.12.10-amd64.exe
    - name: dbschema
      alwaysDownload: Y
      urls:
        - url: https://dbschema.com/jdbc-drivers/CassandraJdbcDriver.zip
        - url: https://dbschema.com/jdbc-drivers/MariaDbJdbcDriver.zip
        - url: https://dbschema.com/jdbc-drivers/MongoDbJdbcDriver.zip
        - url: https://dbschema.com/jdbc-drivers/SqliteJdbcDriver.zip
        - url: https://dbschema.com/jdbc-drivers/H2JdbcDriver.zip
    - name: ack
      urls:
        - url: https://beyondgrep.com/ack-v3.7.0
          name: ack-3.7.0

    url-template-version:
      - name: kafka
        urls:
          - baseurl: https://archive.apache.org/dist/kafka/${version}/kafka_2.12-${version}.tgz
            versions:
              - 3.9.1
          - baseurl: https://archive.apache.org/dist/kafka/${v}/kafka_2.13-${v}.tgz
            template: ${v}
            versions:
              - 4.1.1
              - 3.9.1

    sdkman:
      - name: gradle
      - name: maven
      - name: java
        extension: .tar.gz
        versions:
          - 21.0.9-ms
          - 17.0.17-ms

    github:
      - name: yq
        repo: mikefarah/yq
        assetMatcherQuery: ^yq_linux_amd64$
        filenameStrategy: artifact-version

    jfrog:
      - name: artifact1
        path: releases/com/example/artifact1
      - name: artifact2
        jfrogArtifactName: ArtifactB
        path: releases/com/example/ArtifactB
        extension: .jar
      - name: artifact3
        path: releases/com/example/artifact3
        fileRegex: ^\\/artifact3-.*-jar-with-dependencies.jar$
        extension: .jar
